# creating the deployment YAML file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: anzweb
          image: mchidambaram1990/anz:latest
          imagePullPolicy: Always

---
# Creating the service YAML file for the webapp
kind: Service
apiVersion: v1
metadata:
  name: webservice
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 5000
