apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: anzweb
          image: mchidambaram1990/anz
          imagePullPolicy: "Always"

---
kind: Service
apiVersion: v1
metadata:
  name: webservice
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 5000